# Generated by Django 5.1.4 on 2025-05-09 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'mp4', 'avi', 'jpg', 'jpeg', 'png'])])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_deepfake', models.BooleanField(blank=True, null=True)),
                ('analysis_details', models.TextField(blank=True)),
                ('filename', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
